### ISSUE TITLE
Nginx Proxy Manager Issues

### ISSUE THREAD

**Issue by mikenye** [mikenye/docker-picard#40]
Reported via Discord:

hi guys, installed picard via docker compose and running behind nginx proxy manager. i probably overlooked something since i only get the top bar when accessing the web gui. it's loading for a few seconds and then a red X appears and nothing else. logs seem OK to me. any ideas?

server disconnected: error 1006

```
picard:
#    build: ~/picard
    container_name: picard
    image: mikenye/picard
    ports:
      - "5800:5800"
    environment:
      - PUID=1000
      - PGID=1001
    volumes:
      - "~/picard/config:/config:rw"
      - "/mnt/BX/Music:/storage:rw"
```
