### ISSUE TITLE
Picard for arm chips

### ISSUE THREAD

**Issue by TimmyYung** [mikenye/docker-picard#41]
Currently Picard only supports amd64 chips and was wondering if it was possible for it to support arm chips? This is so that Picard can then run on a raspberry pi.

**Comment by mikenye** [comment]
Adding https://github.com/jlesage/docker-baseimage/issues/1 as a dependency to this issue.

**Comment by kullervo610** [comment]
+1 for this. I am currently experimenting with K3s on RPi and having Picard running on arm64 would be great 👍

**Comment by mikenye** [comment]
@kullervo610 just waiting on the base image author to release their ARM version (which should hopefully be very soon). Once that's done, I will convert this image to multi-arch.

**Comment by jdomenechb** [comment]
@mikenye https://github.com/jlesage/docker-baseimage/issues/1 has been closed

**Comment by Telectroboy** [comment]
Hello,

I'm still not able to run Picard on an Arm chip? (Freebox Delta)

Here is the issue :
```
⠿ Container musicbrainz-picard-1  Created                                                                       4.9s
Attaching to musicbrainz-picard-1
musicbrainz-picard-1  | exec /init: exec format error
```

And my docker-composer.yml

```
version: '3'
services:
  picard:
    image: mikenye/picard:latest
    ports:
      - "4530:5800"
    volumes:
      - "/home/freebox/musicbrainz:/config:rw"
      - "/mnt/Freebox/Musiques:/storage:rw"
```


Is there any solution?

Thanks a lot :)
