### ISSUE TITLE
Container immediately crashes due to /tmp error

### ISSUE THREAD

**Issue by unusualcrow** [mikenye/docker-picard#73]
Running on OpenMediaVault. Found 2 other reports of this issue in the SDR Enthusiasts Discord server, with no solutions.

My docker compose:

```
  picard:
    image: mikenye/picard:latest
    container_name: picard
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}
      - CLEAN_TMP_DIR=0
    volumes:
      - "${ROOT}/config/picard:/config:rw"
      - "${ROOT}/database/Music:/storage:rw"
    ports:
      - 5800:5800
```

vars:
PUID=1002
PGID=1002
TZ=America/New_York
ROOT=/Prim5/Plex

The log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
rm: cannot remove '/tmp/run': Directory not empty
[cont-init.d] 00-clean-tmp-dir.sh: exited 1.
[services.d] stopping services
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

when `CLEAN_TMP_DIR=0` is set in envvars, it fails here instead:

```
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
mkdir: cannot create directory ‘/tmp/run/user/app’: Invalid argument
[cont-init.d] 00-xdg-runtime-dir.sh: exited 1.
```
