### ISSUE TITLE
Network request error

### ISSUE THREAD

**Issue by swoop124** [mikenye/docker-picard#74]
Hello,

i just installed "muicbrainz-picard docker" on my docker-host.
```
version: '3'
services:
  picard:
    image: mikenye/picard:latest
    container_name: musikbrainz
    ports:
      - "5801:5800"
    volumes:
      - "./config:/config:rw"
      - "/mnt/music/Music:/storage:rw"
```
When i start the container i get the following messages:
```
E: 08:19:19,544 /usr/local/lib/python3.6/dist-packages/picard/webservice/__init__._handle_reply:517: Network request error for https://picard.musicbrainz.org/api/v2/releases: Connection closed (QT code 2, HTTP code 0)
E: 08:19:19,545 /usr/local/lib/python3.6/dist-packages/picard/util/checkupdate._releases_json_loaded:103: Error loading Picard releases list: Connection closed
```
I can't get any information for titles i search.

The container itself has internet connetivity. DNS is workin OK

As for versions:
![grafik](https://github.com/mikenye/docker-picard/assets/75502165/d800afca-997b-4110-878f-d841a1237e07)

any advice?
